version: '2'
services:
    etcd:
        build: .
        image: ender74/etcd-arm
        ports:
            - "2379:2379"
            - "2380:2380"
            - "4001:4001"
        volumes:
            - /usr/share/ca-certificates/:/etc/ssl/certs
volumes:
  data-etcd:
